Create a React Component for plotting functions
dantiberi/Fall-2021-IPRO pull request #147
Opened 2022-02-02 01:29 UTC by khiemnguyen22

- Create a react component that has a field to enter the equation and it will return the plot
- Everything is still hard-coded and I will continue working to integrate it to our game

2022-02-07 02:22 UTC, dantiberi requested changes
I think we should keep working on this before adding it to main. Once it's not hardcoded and ready to be used robustly then we can add it to main IMO.

2022-02-25 23:17 UTC, tovaio submitted a review, later dismissed

2022-04-13 00:10 UTC, dantiberi approved these changes

2022-04-13 01:17 UTC, tovaio approved these changes

2022-04-13 01:18 UTC, merged